// Automatically generated by astro-icon
// 37dc033f659d468077794174f3baab252c4ee91fc4afde9e4da7fdeec061cdc8

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "aftereffects"
		| "androidstudio"
		| "animate"
		| "apple"
		| "arc"
		| "archlinux"
		| "assembly"
		| "c"
		| "chatgpt"
		| "chrome"
		| "cpp"
		| "davinci"
		| "firefox"
		| "illustrator"
		| "kalilinux"
		| "markdown"
		| "neovim"
		| "notion"
		| "photoshop"
		| "premiere"
		| "python"
		| "qt"
		| "safari"
		| "shell"
		| "sublime"
		| "tailscale"
		| "typora"
		| "ubuntu"
		| "unity"
		| "vscode"
		| "warp"
		| "windows11"
		| "zerotier";
}